board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.CategoryLV.as_view(), name='index'),
    path('category', views.CategoryLV.as_view(), name='category_list'),
    path('category/<int:pk>/', views.CategoryDV.as_view(), name='category_detail'),
    path('item/<int:pk>/', views.ItemDV.as_view(), name='item_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static # static()는 정적 파일을 처리하기 위해 그에 맞는 URL 패턴을 반환하는 함수
from django.conf import settings # settings 변수를 임포트, settings.py 모듈에서 정의한 항목들을 담고있는 객체를 가리키는 reference

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 기존 URL 패턴에 static() 함수가 반환하는 URL 패턴을 추가한다. 

board/models.py
from django.db import models
from board.fields import ThumbnailImageField

# Create your models here.
class Category(models.Model):
    ct_name = models.CharField(max_length=30)

    
    
class Item(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    it_name = models.CharField(max_length=30)
    description = models.TextField(blank=True)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')

board/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Category, Item

# Create your views here.

class CategoryLV(ListView):
    model = Category

class CategoryDV(DetailView):
    model = Category

class ItemDV(DetailView):
    model = Item

board/templates/board/category_detail.html
<h1>category_detail.html</h1>

<div>
    <h2>{{ object.ct_name }}</h2>
</div>

<br>


{% for item in object.item_set.all %}
<div>
    <a href="{% url 'board:item_detail' item.id %}"><img src="{{ item.image.thumb_url }}"></a>
</div>
<ul>
    <li>{{ item.it_name }}</li>
</ul>
{% endfor %}

board/templates/board/category_list.html
<h1>category_list.html</h1>

<div>
    {% for cate in object_list %}
    <a class="h2" href="{% url 'board:category_detail' cate.id %}">{{cate.ct_name}}</a>
    {% endfor %}
</div>

board/templates/board/item_detail.html
<h1>item_detail.html</h1>

<br>

<h2>{{ object.it_name }}</h2>
<div>
    <a href="{{ object.image.url }}"><img src="{{ object.image.url }}"></a>
</div>

<ul>
    <li>Item description</li>
        {% if object.description %}<p>{{ object.description|linebreaks }}</p>
        {% else %}<p>blank</p>{% endif %}

    <li>Category name</li>
        <a href="{ % url 'board:category_detail' object.category.id %}">{{ object.category.ct_name }}</a>
</ul>